# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/toy_flash_attn',
                'doc_host': 'https://Luan-vP.github.io',
                'git_url': 'https://github.com/Luan-vP/toy_flash_attn',
                'lib_path': 'toy_flash_attn'},
  'syms': {'toy_flash_attn.core': {'toy_flash_attn.core.foo': ('core.html#foo', 'toy_flash_attn/core.py')}}}
